name: Build and Release iOS App

on:
  workflow_dispatch: # Allow manual triggering

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Ask for Repository
      id: repo
      run: |
        echo "::set-output name=REPO::$(read -p 'Enter the GitHub repository (username/repo): ' repo && echo $repo)"

 #   - name: Set up Xcode
 #     uses: actions/setup-xcode@v2
 #     with:
 #       xcode-version: 13

    - name: Install CocoaPods
      run: |
        gem install cocoapods
        pod install

    - name: Build and Archive
      run: |
        xcodebuild archive -workspace YourApp.xcworkspace -scheme YourScheme -archivePath build/YourApp.xcarchive
# Chanhe YourApp.xcworkspace and YourScheme with apparent file name
    - name: Create IPA
      run: |
        xcodebuild -exportArchive -archivePath build/YourApp.xcarchive -exportPath build -exportOptionsPlist ExportOptions.plist

    - name: Upload IPA Artifact
      uses: actions/upload-artifact@v2
      with:
        name: YourApp-iOS
        path: build/YourApp.ipa
